require "./../Generic_funcs/path.rb"

namespace "plotstart" do |ns|

  PLOTSTART = "PlotStART"

  desc "Generating column density map"
  task :column_density, [:inp, :out, :var, :proj, :ftype] do |t,args|
    args.with_defaults(:var => "NHI", :proj => 3, :ftype => "fits")

    if args.inp.nil? or args.out.nil? or args.inp.empty? or args.out.empty?
      error "input and output are mandatory parameters." \
            " `$ rake \"p2c:run[input,output,...]\"`"
      exit
    end

    command = "#{PLOTSTART}"
    command += " -inp #{args.inp} -out #{args.out}"
    command += " -var #{var}" unless args.var.nil?
    command += " -proj #{args.proj}"
    command += " -ftype #{ftype}" unless args.ftype.nil?

    logfile = Path.make_log args.out

    sh "#{command} | tee -a #{logfile}"
  end

  desc "Generating surface density map"
  task :surface_brightness, [:inp, :out, :proj, :ftype] do |t,args|
    args.with_defaults(:proj => 3, :ftype => "fits")

    if args.inp.nil? or args.out.nil? or args.inp.empty? or args.out.empty?
      error "input and output are mandatory parameters." \
            " `$ rake \"p2c:run[input,output,...]\"`"
      exit
    end

    command = "#{PLOTSTART}"
    command += " -inp #{args.inp} -out #{args.out}"
    command += " -var SB_fluor"
    command += " -proj #{args.proj}"
    command += " -ftype #{args.ftype}"

    logfile = Path.make_log args.out

    sh "#{command} | tee -a #{logfile}"
  end
end
