require "./../Generic_funcs/log.rb"
require "./../Generic_funcs/names.rb"
require "./../Generic_funcs/paCage.rb"

namespace "p2c" do

  VER = 1
  SUBVER = 1

  EXEC = "P2C-#{VER}.#{SUBVER}"

  DEVEL_DIR = "~/development"
  LOCAL_DIR = "~/.local"


  desc "Running P2C to convert a particle snapshot to Chombo format"
  task :run, [:inp, :out, :npref, :basegrid, :cut_le, :cut_re] do |t,args|
    args.with_defaults(:npref => 12, :basegrid => 512)

    if args.inp.nil? or args.out.nil? or args.inp.empty? or args.out.empty?
      error "input and output are mandatory parameters." \
            " `$ rake \"p2c:run[input,output,...]\"`"
      exit
    end


    unless args.cut_le.nil? or args.cut_re.nil?
      cutting = "-cut_le #{args.cut_le} -cut_re #{args.cut_re}"
    end


    command = "#{EXEC}"
    command += " -inp #{args.inp} -out #{args.out}"
    command += " -npref #{args.npref}" unless args.npref.nil?
    command += " -base_grid #{args.basegrid}" unless args.basegrid.nil?
    command += " #{cutting}"

    logfile = log_ext args.out

    File.open(logfile, "a") { |f| f.wirte command }

    sh "#{command} | tee -a #{logfile}"
  end


  desc "Compiling P2C application assuming HDF library is already installed"
  task :compile do |t|
    PaCage.cc("#{DEVEL_DIR}/paCage.new", ["High5", "Geagle"])
    cc()
  end


  # Cloning, updating and compiling P2C application
  def cc
    p2c = "P2C"
    expanded_dir = File.expand_path("#{DEVEL_DIR}")

    if Dir.exist?("#{expanded_dir}/#{p2c}")
      command = "cd #{expanded_dir}/#{p2c}"
      command += " && git pull origin \"$(git_current_branch)\""
    else
      command = "mkdir -p #{expanded_dir}"
      command += " && cd #{expanded_dir}"
      command += " && git clone git@github.com:saeedSarpas/P2C.git"
    end

    system command
    system "cd #{expanded_dir}/#{p2c} && make"
  end

end
