require "./../lib/log.rb"
require "./../lib/path.rb"
require "./../lib/paCage.rb"

namespace "p2c" do

  P2C_VER = 1
  P2C_SUBVER = 1

  P2C = "P2C-#{P2C_VER}.#{P2C_SUBVER}"


  desc "Running P2C to convert a particle snapshot to Chombo format"
  task :run, [:inp, :out, :npref, :basegrid, :cut_le, :cut_re] do |t,args|
    args.with_defaults(:npref => 12, :basegrid => 512)

    if args.inp.nil? or args.out.nil? or args.inp.empty? or args.out.empty?
      error "input and output are mandatory parameters." \
            " `$ rake \"p2c:run[input,output,...]\"`"
      exit
    end


    unless args.cut_le.nil? or args.cut_re.nil?
      cutting = "-cut_le #{args.cut_le} -cut_re #{args.cut_re}"
    end


    command = "#{P2C}"
    command += " -inp #{args.inp} -out #{args.out}"
    command += " -npref #{args.npref}" unless args.npref.nil?
    command += " -base_grid #{args.basegrid}" unless args.basegrid.nil?
    command += " #{cutting}"

    logfile = Path.make_log args.out

    File.open(logfile, "a") { |f| f.write command }

    sh "#{command} | tee -a #{logfile}"
  end


  desc "Compiling P2C application assuming HDF library is already installed"
  task :compile do |t|
    PaCage.cc("#{Path.dev}/paCage.new", ["High5", "Geagle"])
    cc()
  end


  # Cloning, updating and compiling P2C application
  def cc
    p2c = "P2C"
    if Dir.exist?("#{Path.dev}/#{p2c}")
      command = "cd #{Path.dev}/#{p2c}"
      command += " && git pull origin \"$(git_current_branch)\""
    else
      command = "mkdir -p #{Path.dev}"
      command += " && cd #{Path.dev}"
      command += " && git clone git@github.com:saeedSarpas/P2C.git"
    end

    system command
    system "cd #{Path.dev}/#{p2c} && make"
  end

end
