require "./../lib/log.rb"
require "./../lib/path.rb"


namespace "radamesh" do |ns|

  RADAMESH_VER = 1
  RADAMESH_SUBVER = 3

  RADAMESH = "Radamesh-#{RADAMESH_VER}.#{RADAMESH_SUBVER}_64"

  desc 'Running "default" Radamesh simulation'
  task :run_default, [:inp, :out, :boxsize, :redshift, :check_params] do |t,args|
    args.with_defaults(:check_params => FALSE)

    if args.inp.nil? or args.out.nil? or args.inp.empty? or args.out.empty?
      error "input and output are mandatory parameters." \
        " `$ rake \"p2c:run[input,output,...]\"`"
      exit
    end

    p = RadameshParams.new

    p.add_block(:runtime, {
      "ActualRun" => ".false.",
      "VersionID" => File.basename(args.out),
      "Verbosity" => "2",
      "FinalRedshift" => args.redshift.to_s,
      "SimulationTime" => "0",
      "InitCollEq" => ".false.",
      "InitNtrFrac" => "1.",
      "InitUVBEq" => ".true.",
      "LightSpeedLimit" => ".true.",
      "DoInitEvol" => ".true.",
      "TimeStepFact" => "0.1",
      "MinTimeStep" => "0.04",
      "KeepBKG" => ".false.",
      "StarThr" => "1.e19",
      "MaxNtrFrac" => "0.0",
    })

    p.add_block(:species, {"NSpecies" => "3"})

    p.add_block(:snapshot, {
      "DensityInputFile" => "\"#{args.inp}\"",
      "ComovingBoxSize" => args.boxsize.to_s,
      "InitialRedshift" => args.redshift.to_s,
    })

    p.add_block(:cosmology, {
      "OmegaBaryonNow" => "0.0482519",
      "OmegaCDMNow" => "0.307",
      "OmegaLambdaNow" => "0.693",
      "HubbleConstNow" => "67.77",
    })

    p.add_block(:background, {
      "Gamma_BKG" => "0.944E-12 0.557E-12 0.128E-13",
      "HeatR_BKG" => "0.375e-11 0.422e-11 0.178e-12",
      "UVB_SS" => ".true.",
      "UVB_SSThr" => "0.005",
    })

    p.add_block(:sources, {
      "NSources" => "1",
      "SourceCoords" => "0.5 0.5 0.5",
      "SpectrumType" => "1",
      "TotalIonRate" => "57.33",
      "SpectrumSlope" => "1.57",
      "InitHIIradius" => "1.e-4",
      "OpAngle" => "0.25",
    })

    p.add_block(:ray_tracing, {
      "NSpectralRegions" => "3",
      "NSpectralBins" => "10 5 5",
      "MinMaxEnergy" => "1 1.8088 1.8088 4 4 8",
      "NRays" => "5",
      "MaxTau" => "50 50 50",
      "SafetyDist" => "10.0",
      "InterpTauDiff" => "0.1 1.e9 1.e9",
      "MinIntpDist" => "0.02",
      "ConvThr" => "0.1",
      "MinTau" => "0.1 1.e9 1.e9",
      "MinTauDiff" => "0.1 1.e9 1.e9",
      "MinTauCell" => "0.1 1.e9 1.e9",
      "ATSFreq" => "5",
      "ATSFact" => "1.e4",
    })

    p.add_block(:output, {
      "NTimeSteps" => "1",
      "OutputFreqStep" => "0",
      "NOutputs" => "1",
      "OutputTimeStep" => "0",
    })

    path = Path.make_config args.out
    p.write(path)

    if args.check_params
      sh "$EDITOR #{path}"
    end

    logfile = Path.make_log args.out

    command = "cat #{path} >> #{logfile}"
    command += " && cd #{File.split(logfile)[0]}"
    command += " && #{RADAMESH} ./#{File.basename paramfile}"
    command += " | tee -a #{logfile}"

    sh command
  end
end
