require './../Generic_funcs/path.rb'
require './ramses.rb'

namespace 'ramses' do
  RAMSES = 'ramses'.freeze
  RAMSES_GIT = 'https://bitbucket.org/rteyssie/ramses'.freeze
  RAMSES_NDIM = 3

  desc 'Compiling RAMSEST'
  task :compile, [:type, :solver, :patch] do |_, args|
    args.with_defaults(type: 'rt', solver: 'hydro', patch: '')

    clone
    r = Ramses.new RAMSES_NDIM, args.patch
    r.makefile("#{Path.dev}/#{RAMSES}/bin/Makefile.new",
      args.type.to_sym, args.solver.to_sym)

    sh "cd #{Path.dev}/#{RAMSES}/bin && make -f Makefile.new"

    sh "cp #{Path.dev}/#{RAMSES}/bin/ramses#{RAMSES_NDIM}d #{Path.local}/bin"
  end

  def self.clone
    if Dir.exist? "#{Path.dev}/#{RAMSES}"
      command = "cd #{Path.dev}/#{RAMSES}"
      command += ' && git pull origin \"$(git_current_branch)\"'
    else
      command = "mkdir -p #{Path.dev}"
      command += " && git clone #{RAMSES_GIT} #{Path.dev}/#{RAMSES}"
    end

    system command
  end
end
