namespace "rvm" do
  RC_FILE = ".zshrc.local"

  task :install do
    sh "gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
    sh "\\curl -sSL https://get.rvm.io | bash -s stable"

    File.open("~/#{RC_FILE}", "a") { |f|
      f.write("source /net/theia/scratch/saeed/.rvm/scripts/rvm")
      f.write("export PATH=${HOME}/.gem/ruby/2.3.0//bin:$PATH")
    }

    sh "rvm autolibs disable"
    sh "rvm requirements"

    sh "source ${HOME}/#{RC_FILE}"

    sh "rvm install 2.4.1-dev"
  end
end
